In [5]:
#########Numpy 

import numpy as np

arr = np.array([10, 20, 30])
print(arr)          # [10 20 30]
print(type(arr))
print(np.mean(arr)) # Average nikal dega





[10 20 30]
<class 'numpy.ndarray'>
20.0


In [ ]:
#print(arr[1])
arr.ndim ## this will tell of dimention
print(arr.dtype) 

int64


In [17]:
#2 dimention Array

da=np.array([[1,2,3],[4,5,6]])

da.ndim

2

In [19]:
tda=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
tda.ndim

3

In [21]:
np.zeros((3,4)) #this will use to make metrix of 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,2)) #to make of 1 metrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [ ]:
a1+a2  ## this can't be perform using list thats why we will use array

array([5, 7, 9])

In [ ]:
a3=np.array([[1,2],[4,5]])
a4=np.array([[4,5],[8,2]])


In [36]:
print(a3)

#np.dot(a3,a4)
#np.linalg.inv()
#np.mean()
#np.std() standard diviation



[[1 2 3]
 [4 5 6]]


In [37]:
b=a3*a4

print(b)

[[ 4 10 18]
 [32 10 24]]
