In [5]:
##################Quiz Prepreation###############

import numpy as np  ## this library is use to deal with numerical values

In [19]:
Array1=np.array([[1,2,3],[2,3,4]])

print(Array1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(Array1.ndim) ####this is use to show dimentions of array

print(Array1.size) #### To show no of elements

print(Array1.shape) #### To show no of rows and column

print(Array1.dtype) #### To show data type of array

2
6
(2, 3)
int64


In [ ]:
######### Comparision of list and arrays############

list1=(1,2,3)
lits2=(3,4,5)

list3=list1+lits2

print(list3)         #############List will merge both lists

arr1=np.array([1,2,3])
arr2=np.array([2,3,4])

arr3=arr1+arr2

print(arr3)          ############### Array will perform addision of matrixes of arrays

(1, 2, 3, 3, 4, 5)
[3 5 7]


In [26]:
######### Slicing and indexing############

arr0=np.array([1,2,3,4,5])
print(arr0[1])

print(arr0[1:4])

2
[2 3 4]


In [36]:
######### copy vs view ############

arr = np.array([1, 2, 3])
copy_arr = arr.copy()

copy_arr[0] = 100

print(arr)       # [1 2 3]   (NO CHANGE)
print(copy_arr)



[1 2 3]
[100   2   3]


In [ ]:
arr = np.array([1, 2, 3])
V_arr = arr.view()

V_arr[0] = 100

print(arr)       
print(V_arr)

[100   2   3]
[100   2   3]


In [45]:
###Reshap Function

a=np.array([1,2,3,4,5,6])
print(a.shape)

b=a.reshape(2,3)     ##### reshap k lia element size same hona chaya men a ka size 4 tha ab 2,2 ki e bna skty
print(b)


(6,)
[[1 2 3]
 [4 5 6]]


In [48]:
a=np.random.randint(2,20,30)
print(a)
 
      

[11  2  9 18  9 15 11 14 18 15 14 17 19  9 15 12  7  5 15 14  4  9  8 13
  3 16 19 17  9  7]


In [53]:
arrr=np.array([2,3,4,5])

a=np.random.choice(arrr,2)  #array k size sy ziada b size dhy skty

print(a)

[3 4]


In [ ]:

a=np.identity(6) ### Rows r column 
print(a)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b=np.transpose(A)

print(b)


[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [69]:
arry1=np.array([1,2,3])
arry2=np.array([3,4,6]) ### if there will be 2d array rows*colm 
arry3 = np.array([[3, 4],    ##### Inverse will be perform when there will be square matrix no of rows and columns should same 
                  [1, 6]])

dot_prod=np.dot(arry1,arry2)
Inv_arr=np.linalg.inv(arry3)
determinant_arry3=np.linalg.det(arry3)
print(Inv_arr)

print(dot_prod)
print(determinant_arry3)


[[ 0.42857143 -0.28571429]
 [-0.07142857  0.21428571]]
29
14.000000000000004


In [79]:

AA= np.array([[12,80,36],
              [2, 4, 6],
              [10,20,30]])
arr_rank=np.linalg.matrix_rank(AA)

print(arr_rank)
print(AA.trace())  ### this will sum diaginal 
print(AA.flatten()) ### This will convert matrixes in a row

2
46
[12 80 36  2  4  6 10 20 30]


In [90]:
aaa=np.array([1,2,3])

array_sum=np.sum(aaa)
array_mean=np.mean(aaa)
array_standarddev=np.std(aaa)
array_min=np.min(aaa)
array_max=np.max(aaa)
array_minargs=np.argmin(aaa)  ## ye min value ka index bttata
array_maxargs=np.argmax(aaa)  ## ye max value ka index bttata



print(array_sum)
print(array_mean)
print(array_standarddev)
print(array_min)
print(array_max)
print(array_minargs)
print(array_maxargs)


6
2.0
0.816496580927726
1
3
0
2


In [ ]:
###### Axis parameter

ax_array= np.array([[12,80,36],
              [2, 4, 6],
              [10,20,30]])

col_sum=np.sum(ax_array,axis=0)
row_sum=np.sum(ax_array, axis=1)


print(col_sum)
print(row_sum)


[ 24 104  72]
[128  12  60]


In [107]:
##################### Panda ##########

import pandas as pd

##  data convert to dataframe mean convert to table

data = {"Name": ["Ali", "Sara", "John","Aqib","Saqib","Rakish"],
        "Age": [20, 21, 19,23,25,27],
        "Marks": [85, 90, 88, 66,78,89]}

print("Before Dataframe")
print(data)

tb=pd.DataFrame(data)
print("after Data Frame")
print(tb)




Before Dataframe
{'Name': ['Ali', 'Sara', 'John', 'Aqib', 'Saqib', 'Rakish'], 'Age': [20, 21, 19, 23, 25, 27], 'Marks': [85, 90, 88, 66, 78, 89]}
after Data Frame
     Name  Age  Marks
0     Ali   20     85
1    Sara   21     90
2    John   19     88
3    Aqib   23     66
4   Saqib   25     78
5  Rakish   27     89


In [ ]:
fisrt_5col=tb.head()  ## by pass a num can spacify how many columns should show and this will work only on table not discioanry

last_5col=tb.tail() ## Last 5 records

detail_colms=tb.describe() 

colmn_names= tb.columns

Index_info=tb.index  ## indexes info from where start,end and gap between


print(fisrt_5col)
print(last_5col)
print(detail_colms)
print(colmn_names)
print(Index_info)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Age     6 non-null      int64 
 2   Marks   6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes
    Name  Age  Marks
0    Ali   20     85
1   Sara   21     90
2   John   19     88
3   Aqib   23     66
4  Saqib   25     78
     Name  Age  Marks
1    Sara   21     90
2    John   19     88
3    Aqib   23     66
4   Saqib   25     78
5  Rakish   27     89
             Age      Marks
count   6.000000   6.000000
mean   22.500000  82.666667
std     3.082207   9.244818
min    19.000000  66.000000
25%    20.250000  79.750000
50%    22.000000  86.500000
75%    24.500000  88.750000
max    27.000000  90.000000
Index(['Name', 'Age', 'Marks'], dtype='object')
RangeIndex(start=0, stop=6, step=1)
None


In [115]:
Info_dataset=tb.info()

print(Info_dataset)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Age     6 non-null      int64 
 2   Marks   6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes
None


In [116]:
###########################   sqllite  ######################

import sqlite3 as sq

In [117]:
conn=sq.Connection("Quizprep.db")


In [118]:
cur=conn.cursor()

In [119]:
cur.execute(''' Create table if not exists quizpre(id int,name string,rollno int)''' )